In [1]:
import torch 
import numpy as np 
import pandas as pd

In [2]:
data_train  = pd.read_csv("train_FD001.txt")

In [3]:
data_test = pd.read_csv("test_FD001.txt")

In [4]:
data_RUL = pd.read_csv("RUL_FD001.txt")

In [5]:
data_train

      1 1 -0.0007 -0.0004 100.0 518.67 641.82 1589.70 1400.60 14.62 21.61 554.36 2388.06 9046.19 1.30 47.47 521.66 2388.02 8138.62 8.4195 0.03 392 2388 100.00 39.06 23.4190
0      1 2 0.0019 -0.0003 100.0 518.67 642.15 1591.82...
1      1 3 -0.0043 0.0003 100.0 518.67 642.35 1587.99...
2      1 4 0.0007 0.0000 100.0 518.67 642.35 1582.79 ...
3      1 5 -0.0019 -0.0002 100.0 518.67 642.37 1582.8...
4      1 6 -0.0043 -0.0001 100.0 518.67 642.10 1584.4...
...                                                  ...
20625  100 196 -0.0004 -0.0003 100.0 518.67 643.49 15...
20626  100 197 -0.0016 -0.0005 100.0 518.67 643.54 16...
20627  100 198 0.0004 0.0000 100.0 518.67 643.42 1602...
20628  100 199 -0.0011 0.0003 100.0 518.67 643.23 160...
20629  100 200 -0.0032 -0.0005 100.0 518.67 643.85 16...

[20630 rows x 1 columns]

In [6]:
# this makes no sense once we look at the data we see that the data is not comma seperated but space seperated 
# also we have no col names in files so 
data_train = pd.read_csv("train_FD001.txt",sep = r"\s+",header = None)
data_test  = pd.read_csv("test_FD001.txt",sep = r"\s+",header = None)
data_RUL = data_RUL = pd.read_csv("RUL_FD001.txt",sep = r"\s+",header = None )

In [7]:
data_train

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [8]:
cols = [
    "engine_id", "cycle",
    "op1", "op2", "op3",
] + [f"s{i}" for i in range(1, 22)]

data_train.columns = cols
data_test.columns = cols
data_RUL.columns = ["RUL"]

In [9]:
# the above cell is not my work  it has been found online by the anlaysers and creators of this dataset brought in together with ai

In [10]:
data_train.head()

,engine_id,cycle,op1,op2,op3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [11]:
data_train

,engine_id,cycle,op1,op2,op3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [12]:
# rul is defined as max_cycle_of_the_engine - current_cycle

In [13]:
# so let us take a step back and understand the data 
# first train one it contains for  a engine every cycle until it fails 
# then second one contains for certain steps not until failure 
# then the last one conatins rul of the test dataset not all the time steps only from where we left in test that rul calculated

In [14]:
# calculate rul first that basically lets the model know the the u know the degrading happeing based on changes in features 
# so lets get to train data

In [15]:

for  i in range(len(data_train)):
   curr = data_train["engine_id"].iloc[i]
   j = i  
   while  (j< len(data_train)) and data_train["engine_id"].iloc[j] ==curr :
       j+=1
   else:
       death_stamp = data_train["cycle"].iloc[j-1]
       for k in range(i,j):
        data_train.at[k, "RUL"] =  death_stamp-data_train["cycle"].iloc[k]

In [16]:
data_train

,engine_id,cycle,op1,op2,op3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,191.0
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,190.0
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,189.0
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,188.0
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,187.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735,4.0
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594,3.0
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333,2.0
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640,1.0
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522,0.0

In [17]:
# verification 
max_cycle = data_train.groupby("engine_id")["cycle"].transform("max")

print(((data_train["cycle"] + data_train["RUL"]) == max_cycle).all())
# so ya the handwritten function works perfectly

True

In [18]:
# now let us do a bit of EDA and eliminate some sensors that dont help us 

# so basicaaly we are looking for sensors having zero variance (close to) i.e are almost constant 
data_train.describe()

,engine_id,cycle,op1,op2,op3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,RUL
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,20631.00,20631.000000,20631.000000,20631.000000,2.063100e+04,...,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,100.0,518.67,642.680934,1590.523119,1408.933782,1.462000e+01,...,2388.096152,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705,107.807862
std,29.227633,68.880990,0.002187,0.000293,0.0,0.00,0.500053,6.131150,9.000605,1.776400e-15,...,0.071919,19.076176,0.037505,1.387812e-17,1.548763,0.0,0.0,0.180746,0.108251,68.880990
min,1.000000,1.000000,-0.008700,-0.000600,100.0,518.67,641.210000,1571.040000,1382.250000,1.462000e+01,...,2387.880000,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200,0.000000
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,518.67,642.325000,1586.260000,1402.360000,1.462000e+01,...,2388.040000,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800,51.000000
50%,52.000000,104.000000,0.000000,0.000000,100.0,518.67,642.640000,1590.100000,1408.040000,1.462000e+01,...,2388.090000,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900,103.000000
75%,77.000000,156.000000,0.001500,0.000300,100.0,518.67,643.000000,1594.380000,1414.555000,1.462000e+01,...,2388.140000,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800,155.000000
max,100.000000,362.000000,0.008700,0.000600,100.0,518.67,644.530000,1616.910000,1441.490000,1.462000e+01,...,2388.560000,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400,361.000000

In [19]:
# clealry sensors 
"""s1
s5
s6
s10
s12
s13
s16
s18
s19  are safe to ignore """

's1\ns5\ns6\ns10\ns12\ns13\ns16\ns18\ns19  are safe to ignore '

In [20]:
# now let us remove these sensors from both data_train and data_test 
data_train = data_train.drop(columns = ['s1','s5','s6','s10','s12','s13','s16','s18','s19'])
data_test  = data_test.drop(columns = ['s1','s5','s6','s10','s12','s13','s16','s18','s19'])

In [21]:
data_train.head()

,engine_id,cycle,op1,op2,op3,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
0,1,1,-0.0007,-0.0004,100.0,641.82,1589.70,1400.60,554.36,2388.06,9046.19,47.47,8138.62,8.4195,392,39.06,23.4190,191.0
1,1,2,0.0019,-0.0003,100.0,642.15,1591.82,1403.14,553.75,2388.04,9044.07,47.49,8131.49,8.4318,392,39.00,23.4236,190.0
2,1,3,-0.0043,0.0003,100.0,642.35,1587.99,1404.20,554.26,2388.08,9052.94,47.27,8133.23,8.4178,390,38.95,23.3442,189.0
3,1,4,0.0007,0.0000,100.0,642.35,1582.79,1401.87,554.45,2388.11,9049.48,47.13,8133.83,8.3682,392,38.88,23.3739,188.0
4,1,5,-0.0019,-0.0002,100.0,642.37,1582.85,1406.22,554.00,2388.06,9055.15,47.28,8133.80,8.4294,393,38.90,23.4044,187.0

In [22]:
data_test.head()

,engine_id,cycle,op1,op2,op3,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21
0,1,1,0.0023,0.0003,100.0,643.02,1585.29,1398.21,553.90,2388.04,9050.17,47.20,8125.55,8.4052,392,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,641.71,1588.45,1395.42,554.85,2388.01,9054.42,47.50,8139.62,8.3803,393,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,642.46,1586.94,1401.34,554.11,2388.05,9056.96,47.50,8130.10,8.4441,393,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,642.44,1584.12,1406.42,554.07,2388.03,9045.29,47.28,8132.90,8.3917,391,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,642.51,1587.19,1401.92,554.16,2388.01,9044.55,47.31,8129.54,8.4031,390,38.99,23.4130

In [23]:
data_train.describe()

,engine_id,cycle,op1,op2,op3,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,100.0,642.680934,1590.523119,1408.933782,553.367711,2388.096652,9065.242941,47.541168,8143.752722,8.442146,393.210654,38.816271,23.289705,107.807862
std,29.227633,68.880990,0.002187,0.000293,0.0,0.500053,6.131150,9.000605,0.885092,0.070985,22.082880,0.267087,19.076176,0.037505,1.548763,0.180746,0.108251,68.880990
min,1.000000,1.000000,-0.008700,-0.000600,100.0,641.210000,1571.040000,1382.250000,549.850000,2387.900000,9021.730000,46.850000,8099.940000,8.324900,388.000000,38.140000,22.894200,0.000000
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,642.325000,1586.260000,1402.360000,552.810000,2388.050000,9053.100000,47.350000,8133.245000,8.414900,392.000000,38.700000,23.221800,51.000000
50%,52.000000,104.000000,0.000000,0.000000,100.0,642.640000,1590.100000,1408.040000,553.440000,2388.090000,9060.660000,47.510000,8140.540000,8.438900,393.000000,38.830000,23.297900,103.000000
75%,77.000000,156.000000,0.001500,0.000300,100.0,643.000000,1594.380000,1414.555000,554.010000,2388.140000,9069.420000,47.700000,8148.310000,8.465600,394.000000,38.950000,23.366800,155.000000
max,100.000000,362.000000,0.008700,0.000600,100.0,644.530000,1616.910000,1441.490000,556.060000,2388.560000,9244.590000,48.530000,8293.720000,8.584800,400.000000,39.430000,23.618400,361.000000

In [24]:
# now lets look at the operating conditions 
# clearly op3 is of no help 
data_train.isnull().sum()

engine_id    0
cycle        0
op1          0
op2          0
op3          0
s2           0
s3           0
s4           0
s7           0
s8           0
s9           0
s11          0
s14          0
s15          0
s17          0
s20          0
s21          0
RUL          0
dtype: int64

In [25]:
# lets drop op3 
data_train = data_train.drop(columns =["op3"])
data_test = data_test.drop(columns =["op3"])

In [26]:
data_train

,engine_id,cycle,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,554.36,2388.06,9046.19,47.47,8138.62,8.4195,392,39.06,23.4190,191.0
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,553.75,2388.04,9044.07,47.49,8131.49,8.4318,392,39.00,23.4236,190.0
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,554.26,2388.08,9052.94,47.27,8133.23,8.4178,390,38.95,23.3442,189.0
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,554.45,2388.11,9049.48,47.13,8133.83,8.3682,392,38.88,23.3739,188.0
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,554.00,2388.06,9055.15,47.28,8133.80,8.4294,393,38.90,23.4044,187.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,643.49,1597.98,1428.63,551.43,2388.19,9065.52,48.07,8137.60,8.4956,397,38.49,22.9735,4.0
20627,100,197,-0.0016,-0.0005,643.54,1604.50,1433.58,550.86,2388.23,9065.11,48.04,8136.50,8.5139,395,38.30,23.1594,3.0
20628,100,198,0.0004,0.0000,643.42,1602.46,1428.18,550.94,2388.24,9065.90,48.09,8141.05,8.5646,398,38.44,22.9333,2.0
20629,100,199,-0.0011,0.0003,643.23,1605.26,1426.53,550.68,2388.25,9073.72,48.39,8139.29,8.5389,395,38.29,23.0640,1.0
20630,100,200,-0.0032,-0.0005,643.85,1600.38,1432.14,550.79,2388.26,9061.48,48.20,8137.33,8.5036,396,38.37,23.0522,0.0

In [27]:
# now there are some imp things i learnded while reasearching abt when to scale and when not to 
# see we need to scale only for problmes where distance matters not for decision tree based ones 
# when i mean distance i mean rnns lstms linear regression all that
# and also we genraelly split the dataset to train test and validation right always rmeber to never fit a scaler either on 
# validation or test dircetly why it is basically dtaleakng our models histories i.e the trainibg ststs shud be use =d to scal ethe 
# test and validation ones
# this is not just for  scaling or standardization 
"""Any step that computes something from the data, for example:

mean / std (StandardScaler)

min / max (MinMaxScaler)

median (imputation)

PCA components

feature selection thresholds

vocabulary (TF-IDF)

normalization parameters

All of these must be fit on training data only"""

'Any step that computes something from the data, for example:\n\nmean / std (StandardScaler)\n\nmin / max (MinMaxScaler)\n\nmedian (imputation)\n\nPCA components\n\nfeature selection thresholds\n\nvocabulary (TF-IDF)\n\nnormalization parameters\n\nAll of these must be fit on training data only'

In [28]:
# now let us split the data and standardize 
# but while splitting we mut be extra careful as here we shud make sure not mix some time frames of engine betwwn train and validation split 
data_train.tail()

,engine_id,cycle,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
20626,100,196,-0.0004,-0.0003,643.49,1597.98,1428.63,551.43,2388.19,9065.52,48.07,8137.60,8.4956,397,38.49,22.9735,4.0
20627,100,197,-0.0016,-0.0005,643.54,1604.50,1433.58,550.86,2388.23,9065.11,48.04,8136.50,8.5139,395,38.30,23.1594,3.0
20628,100,198,0.0004,0.0000,643.42,1602.46,1428.18,550.94,2388.24,9065.90,48.09,8141.05,8.5646,398,38.44,22.9333,2.0
20629,100,199,-0.0011,0.0003,643.23,1605.26,1426.53,550.68,2388.25,9073.72,48.39,8139.29,8.5389,395,38.29,23.0640,1.0
20630,100,200,-0.0032,-0.0005,643.85,1600.38,1432.14,550.79,2388.26,9061.48,48.20,8137.33,8.5036,396,38.37,23.0522,0.0

In [29]:

# so ya we have 100 engine ids int total so 80 for training and 20 for validation 

engine_ids = data_train['engine_id'].unique()

In [30]:
engine_ids

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [31]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [32]:
np.random.shuffle(engine_ids)

In [33]:
train_ratio = 0.8
n_train = int(len(engine_ids) * train_ratio)

train_engine_ids = engine_ids[:n_train]
val_engine_ids   = engine_ids[n_train:]

In [34]:
train_data = data_train[data_train['engine_id'].isin(train_engine_ids)].copy()
val_data   = data_train[data_train['engine_id'].isin(val_engine_ids)].copy()

In [35]:
train_data

,engine_id,cycle,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,554.36,2388.06,9046.19,47.47,8138.62,8.4195,392,39.06,23.4190,191.0
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,553.75,2388.04,9044.07,47.49,8131.49,8.4318,392,39.00,23.4236,190.0
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,554.26,2388.08,9052.94,47.27,8133.23,8.4178,390,38.95,23.3442,189.0
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,554.45,2388.11,9049.48,47.13,8133.83,8.3682,392,38.88,23.3739,188.0
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,554.00,2388.06,9055.15,47.28,8133.80,8.4294,393,38.90,23.4044,187.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,643.49,1597.98,1428.63,551.43,2388.19,9065.52,48.07,8137.60,8.4956,397,38.49,22.9735,4.0
20627,100,197,-0.0016,-0.0005,643.54,1604.50,1433.58,550.86,2388.23,9065.11,48.04,8136.50,8.5139,395,38.30,23.1594,3.0
20628,100,198,0.0004,0.0000,643.42,1602.46,1428.18,550.94,2388.24,9065.90,48.09,8141.05,8.5646,398,38.44,22.9333,2.0
20629,100,199,-0.0011,0.0003,643.23,1605.26,1426.53,550.68,2388.25,9073.72,48.39,8139.29,8.5389,395,38.29,23.0640,1.0
20630,100,200,-0.0032,-0.0005,643.85,1600.38,1432.14,550.79,2388.26,9061.48,48.20,8137.33,8.5036,396,38.37,23.0522,0.0

In [36]:
# indices look broken lets fix that 
train_data.reset_index(drop=True, inplace=True)
val_data.reset_index(drop=True, inplace=True)

In [37]:
train_data

,engine_id,cycle,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,554.36,2388.06,9046.19,47.47,8138.62,8.4195,392,39.06,23.4190,191.0
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,553.75,2388.04,9044.07,47.49,8131.49,8.4318,392,39.00,23.4236,190.0
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,554.26,2388.08,9052.94,47.27,8133.23,8.4178,390,38.95,23.3442,189.0
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,554.45,2388.11,9049.48,47.13,8133.83,8.3682,392,38.88,23.3739,188.0
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,554.00,2388.06,9055.15,47.28,8133.80,8.4294,393,38.90,23.4044,187.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16335,100,196,-0.0004,-0.0003,643.49,1597.98,1428.63,551.43,2388.19,9065.52,48.07,8137.60,8.4956,397,38.49,22.9735,4.0
16336,100,197,-0.0016,-0.0005,643.54,1604.50,1433.58,550.86,2388.23,9065.11,48.04,8136.50,8.5139,395,38.30,23.1594,3.0
16337,100,198,0.0004,0.0000,643.42,1602.46,1428.18,550.94,2388.24,9065.90,48.09,8141.05,8.5646,398,38.44,22.9333,2.0
16338,100,199,-0.0011,0.0003,643.23,1605.26,1426.53,550.68,2388.25,9073.72,48.39,8139.29,8.5389,395,38.29,23.0640,1.0
16339,100,200,-0.0032,-0.0005,643.85,1600.38,1432.14,550.79,2388.26,9061.48,48.20,8137.33,8.5036,396,38.37,23.0522,0.0

In [38]:
#vefication of splits 
print("Train engines:", train_data['engine_id'].nunique())
print("Val engines:", val_data['engine_id'].nunique())

Train engines: 80
Val engines: 20

In [39]:
 set(train_data['engine_id']).isdisjoint(set(val_data['engine_id']))

True

In [40]:
# now the scaling as we found out earlier first start with train_data fit the scaler reamong val and test we just transform 
data_test

,engine_id,cycle,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21
0,1,1,0.0023,0.0003,643.02,1585.29,1398.21,553.90,2388.04,9050.17,47.20,8125.55,8.4052,392,38.86,23.3735
1,1,2,-0.0027,-0.0003,641.71,1588.45,1395.42,554.85,2388.01,9054.42,47.50,8139.62,8.3803,393,39.02,23.3916
2,1,3,0.0003,0.0001,642.46,1586.94,1401.34,554.11,2388.05,9056.96,47.50,8130.10,8.4441,393,39.08,23.4166
3,1,4,0.0042,0.0000,642.44,1584.12,1406.42,554.07,2388.03,9045.29,47.28,8132.90,8.3917,391,39.00,23.3737
4,1,5,0.0014,0.0000,642.51,1587.19,1401.92,554.16,2388.01,9044.55,47.31,8129.54,8.4031,390,38.99,23.4130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,643.24,1599.45,1415.79,553.41,2388.02,9142.37,47.69,8213.28,8.4715,394,38.65,23.1974
13092,100,195,-0.0011,-0.0001,643.22,1595.69,1422.05,553.22,2388.05,9140.68,47.60,8210.85,8.4512,395,38.57,23.2771
13093,100,196,-0.0006,-0.0003,643.44,1593.15,1406.82,553.04,2388.11,9146.81,47.57,8217.24,8.4569,395,38.62,23.2051
13094,100,197,-0.0038,0.0001,643.26,1594.99,1419.36,553.37,2388.07,9148.85,47.61,8220.48,8.4711,395,38.66,23.2699
13095,100,198,0.0013,0.0003,642.95,1601.62,1424.99,552.48,2388.06,9155.03,47.80,8214.64,8.4903,396,38.70,23.1855

In [41]:
# defining what we want to be scaled 
feature_cols = ['op1', 'op2',
    's2', 's3', 's4', 's7', 's8', 's9',
    's11', 's14', 's15', 's17', 's20', 's21']
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(train_data[feature_cols])
train_data_scaled = train_data.copy()
val_data_scaled = val_data.copy()
test_data_scaled = data_test.copy()
train_data_scaled [feature_cols]= scaler.transform(train_data[feature_cols])
val_data_scaled[feature_cols] = scaler.transform(val_data[feature_cols])
test_data_scaled[feature_cols] = scaler.transform(data_test[feature_cols])

In [42]:
val_data_scaled

,engine_id,cycle,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
0,2,1,-0.818057,2.035468,-1.599375,-1.109383,-1.980060,1.330137,-1.221306,-0.505398,-2.305583,-0.346698,-1.397951,-1.445213,0.700833,1.573996,286.0
1,2,2,1.967383,-1.031153,-1.739618,-0.584070,-1.774054,1.601898,-1.644336,-0.656980,-1.143798,-0.687921,-0.697398,-0.798481,1.366421,1.112154,285.0
2,2,3,0.825809,1.013261,-2.280555,-0.376236,-1.124860,2.020863,-0.798277,-0.526735,-1.218752,-0.199504,-1.673359,-1.445213,1.643749,1.264562,284.0
3,2,4,1.602079,-1.371889,-2.020103,-1.058652,-1.445560,1.013083,-1.644336,-0.359151,-1.668475,-0.206709,-1.095804,-1.445213,1.754681,1.982265,283.0
4,2,5,0.232191,1.353997,-1.919930,-1.896534,-0.728439,1.998216,-0.939287,-0.352928,-1.106321,-0.400738,-1.499558,-2.091945,2.032009,1.249783,282.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4286,93,151,1.556416,-0.690417,1.485969,1.319166,3.086556,-2.542452,2.303941,-0.142225,1.704448,-0.306040,1.786622,2.435180,-2.294314,-2.529937,4.0
4287,93,152,0.643157,0.331790,1.806524,1.202975,1.941835,-2.055548,1.316872,-0.277804,2.154171,-0.555137,2.059357,1.141716,-1.961520,-1.552678,3.0
4288,93,153,1.099787,-0.008946,2.167149,1.464813,2.201290,-1.534673,3.008991,0.110263,2.154171,-0.051795,1.783948,2.435180,-1.351397,-1.379025,2.0
4289,93,154,-0.133113,-0.349682,2.107045,2.322333,3.268063,-2.893477,1.739902,-0.195123,2.229124,-0.101203,2.366851,1.788448,-2.848970,-2.076408,1.0
4290,93,155,2.150034,1.013261,1.526038,2.127591,2.180133,-2.950093,1.598892,0.126266,2.453986,-0.383754,1.209067,1.788448,-2.072451,-1.572076,0.0

In [43]:
val_data_scaled.describe()

,engine_id,cycle,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21,RUL
count,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000,4291.000000
mean,54.325332,113.182242,-0.000838,-0.004499,-0.070981,-0.075478,-0.068453,0.067484,0.002729,-0.180933,-0.072662,-0.174122,-0.081821,-0.074581,0.070003,0.071471,112.182242
std,30.811306,71.857174,0.994176,0.993083,1.006846,1.013811,1.008960,1.008854,1.004632,0.893870,1.002530,0.895751,1.010937,1.005648,1.010152,0.997480,71.857174
min,2.000000,1.000000,-3.968800,-2.053360,-2.961734,-2.880064,-2.595848,-3.255824,-2.631405,-1.877633,-2.567921,-2.291100,-2.860555,-2.738677,-3.237230,-3.157119,0.000000
25%,24.000000,54.000000,-0.658237,-0.690417,-0.777952,-0.775540,-0.784673,-0.572187,-0.657267,-0.685873,-0.769029,-0.710051,-0.804353,-0.798481,-0.574878,-0.540319,53.000000
50%,61.000000,108.000000,0.003876,-0.008946,-0.156876,-0.166766,-0.192825,0.186478,-0.093227,-0.350705,-0.206875,-0.275674,-0.200059,-0.151749,0.201642,0.155216,107.000000
75%,85.000000,162.500000,0.688820,1.013261,0.544338,0.545107,0.553248,0.786616,0.611822,-0.013536,0.505186,0.043418,0.536590,0.494984,0.756299,0.778703,161.500000
max,93.000000,341.000000,3.976552,2.035468,3.249023,3.602067,3.611034,2.836145,3.432021,5.842354,3.653247,5.706784,3.765282,3.728644,3.307720,2.885629,340.000000

In [44]:
import joblib
joblib.dump(scaler, "scaler_fd001.pkl")

['scaler_fd001.pkl']

In [45]:
# saving scaler just for safety

In [46]:
from torch.utils.data import TensorDataset , DataLoader

In [47]:
TARGET_COL = 'RUL'
X_train = train_data_scaled[feature_cols ]
y_train = train_data_scaled[TARGET_COL]
X_val = val_data_scaled[feature_cols ]
y_val = val_data_scaled[TARGET_COL]
X_test = test_data_scaled[feature_cols ]
#y_test = will  get to it later

In [48]:
X_train

,op1,op2,s2,s3,s4,s7,s8,s9,s11,s14,s15,s17,s20,s21
0,-0.315765,-1.371889,-1.739618,-0.150401,-0.942239,1.137640,-0.516257,-0.884574,-0.281829,-0.300378,-0.622530,-0.798481,1.366421,1.209141
1,0.871472,-1.031153,-1.078473,0.196535,-0.659399,0.446915,-0.798277,-0.978812,-0.206875,-0.667334,-0.293645,-0.798481,1.033627,1.251630
2,-1.959631,1.013261,-0.677779,-0.430241,-0.541364,1.024407,-0.234237,-0.584523,-1.031368,-0.577782,-0.667986,-2.091945,0.756299,0.518224
3,0.323517,-0.008946,-0.677779,-1.281214,-0.800819,1.239551,0.188793,-0.738327,-1.556044,-0.546903,-1.994223,-0.798481,0.368039,0.792559
4,-0.863720,-0.690417,-0.637709,-1.271396,-0.316428,0.729999,-0.516257,-0.486284,-0.993891,-0.548446,-0.357817,-0.151749,0.478970,1.074283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16335,-0.178776,-1.031153,1.606177,1.204611,2.179019,-2.180105,1.316872,-0.025316,1.966786,-0.352874,1.412281,2.435180,-1.795123,-2.905877
16336,-0.726731,-1.712624,1.706351,2.271602,2.730222,-2.825536,1.880912,-0.043541,1.854355,-0.409487,1.901598,1.141716,-2.848970,-1.188746
16337,0.186528,-0.008946,1.465934,1.937758,2.128910,-2.734950,2.021922,-0.008424,2.041740,-0.175315,3.257248,3.081912,-2.072451,-3.277199
16338,-0.498416,1.013261,1.085275,2.395975,1.945175,-3.029357,2.162932,0.339191,3.166047,-0.265896,2.570065,1.141716,-2.904436,-2.069942
16339,-1.457338,-1.712624,2.327426,1.597369,2.569872,-2.904800,2.303941,-0.204902,2.453986,-0.366770,1.626190,1.788448,-2.460711,-2.178937

In [49]:
# the reason why we neglected engine_id becos it has no physical meaning as we dont want the model to learn that engine 23 is bad becos
# its just an index and why we removed i mean neglected the cycle is becos the time stamos are not absolute we dont want the model to learn 
# that around an avg of this cycle they start degrading and also sensors include the info this idea is fine for the first one 
# as the sensors are too noisy as claimed online if not i will reatrain the model using cycles

In [50]:
WINDOW_SIZE = 30

In [51]:
def create_sequences(df, window_size, feature_cols, target_col):
    X, y = [], []

    for engine_id in df['engine_id'].unique():
        engine_df = df[df['engine_id'] == engine_id]

        features = engine_df[feature_cols].values
        targets  = engine_df[target_col].values

        for i in range(len(engine_df) - window_size + 1):
            X.append(features[i:i+window_size])
            y.append(targets[i+window_size-1])

    return np.array(X), np.array(y)

In [52]:
X_train_seq, y_train_seq = create_sequences(
    train_data_scaled,
    WINDOW_SIZE,
    feature_cols,
    TARGET_COL
)

X_val_seq, y_val_seq = create_sequences(
    val_data_scaled,
    WINDOW_SIZE,
    feature_cols,
    TARGET_COL
)

In [53]:
X_train_seq

array([[[-0.31576458, -1.37188874, -1.73961769, ..., -0.79848052,
          1.36642109,  1.20914067],
        [ 0.87147201, -1.03115302, -1.07847258, ..., -0.79848052,
          1.03362702,  1.25163019],
        [-1.95963063,  1.01326127, -0.67777857, ..., -2.09194455,
          0.75629863,  0.51822411],
        ...,
        [-1.09203466,  1.6947327 , -0.67777857, ..., -2.09194455,
          1.0890927 , -0.03691072],
        [ 0.55183139, -0.34968159, -1.55930539, ..., -0.1517485 ,
          0.64536727,  0.66139532],
        [-1.00070877, -0.00894588, -0.97829908, ..., -2.09194455,
          1.31095541,  1.13524585]],

       [[ 0.87147201, -1.03115302, -1.07847258, ..., -0.79848052,
          1.03362702,  1.25163019],
        [-1.95963063,  1.01326127, -0.67777857, ..., -2.09194455,
          0.75629863,  0.51822411],
        [ 0.32351666, -0.00894588, -0.67777857, ..., -0.79848052,
          0.36803888,  0.79255862],
        ...,
        [ 0.55183139, -0.34968159, -1.55930539, ..., -0.1517485 ,
          0.64536727,  0.66139532],
        [-1.00070877, -0.00894588, -0.97829908, ..., -2.09194455,
          1.31095541,  1.13524585],
        [ 0.64315728,  1.6947327 , -1.33892368, ..., -0.79848052,
          0.70083295,  0.43601612]],

       [[-1.95963063,  1.01326127, -0.67777857, ..., -2.09194455,
          0.75629863,  0.51822411],
        [ 0.32351666, -0.00894588, -0.67777857, ..., -0.79848052,
          0.36803888,  0.79255862],
        [-0.86371993, -0.69041731, -0.63770917, ..., -0.1517485 ,
          0.47897024,  1.07428262],
        ...,
        [-1.00070877, -0.00894588, -0.97829908, ..., -2.09194455,
          1.31095541,  1.13524585],
        [ 0.64315728,  1.6947327 , -1.33892368, ..., -0.79848052,
          0.70083295,  0.43601612],
        [ 0.23219077, -1.03115302, -0.71784797, ..., -0.79848052,
          1.14455838,  1.95640203]],

       ...,

       [[-0.86371993, -1.03115302,  0.32395645, ...,  1.14171553,
         -0.57487766, -0.66501669],
        [-1.54866411,  1.01326127,  0.04347064, ...,  0.49498351,
         -1.01860309, -1.21738046],
        [-0.22443869, -1.37188874,  0.72465045, ...,  1.78844755,
         -0.02022087, -1.26356472],
        ...,
        [-0.17877574, -1.03115302,  1.60617727, ...,  2.43517956,
         -1.79512259, -2.90587708],
        [-0.72673109, -1.71262446,  1.70635077, ...,  1.14171553,
         -2.84897048, -1.18874622],
        [ 0.18652782, -0.00894588,  1.46593437, ...,  3.08191158,
         -2.07245098, -3.27719855]],

       [[-1.54866411,  1.01326127,  0.04347064, ...,  0.49498351,
         -1.01860309, -1.21738046],
        [-0.22443869, -1.37188874,  0.72465045, ...,  1.78844755,
         -0.02022087, -1.26356472],
        [-1.68565295,  0.33178984,  0.56437285, ...,  0.49498351,
         -1.79512259, -0.88577746],
        ...,
        [-0.72673109, -1.71262446,  1.70635077, ...,  1.14171553,
         -2.84897048, -1.18874622],
        [ 0.18652782, -0.00894588,  1.46593437, ...,  3.08191158,
         -2.07245098, -3.27719855],
        [-0.49841636,  1.01326127,  1.08527506, ...,  1.14171553,
         -2.90443616, -2.06994194]],

       [[-0.22443869, -1.37188874,  0.72465045, ...,  1.78844755,
         -0.02022087, -1.26356472],
        [-1.68565295,  0.33178984,  0.56437285, ...,  0.49498351,
         -1.79512259, -0.88577746],
        [ 0.27785372,  1.35399699,  1.42586497, ..., -0.1517485 ,
         -2.18338234, -1.00493285],
        ...,
        [ 0.18652782, -0.00894588,  1.46593437, ...,  3.08191158,
         -2.07245098, -3.27719855],
        [-0.49841636,  1.01326127,  1.08527506, ...,  1.14171553,
         -2.90443616, -2.06994194],
        [-1.45733822, -1.71262446,  2.32742648, ...,  1.78844755,
         -2.46071073, -2.1789368 ]]], shape=(14020, 30, 14))

In [54]:
def create_test_sequences(df, window_size, feature_cols):
    X = []
    engine_ids = []

    for engine_id in df['engine_id'].unique():
        engine_df = df[df['engine_id'] == engine_id]

        features = engine_df[feature_cols].values

        X.append(features[-window_size:])
        engine_ids.append(engine_id)

    return np.array(X), engine_ids

In [55]:
X_test_seq, test_engine_ids = create_test_sequences(
    test_data_scaled,
    WINDOW_SIZE,
    feature_cols
)

In [56]:
import pandas as pd

rul_test = pd.read_csv("RUL_FD001.txt", header=None)
y_test = rul_test[0].values

In [57]:
train_dataset = TensorDataset(
    torch.tensor(X_train_seq, dtype=torch.float32),
    torch.tensor(y_train_seq, dtype=torch.float32)
)

val_dataset = TensorDataset(
    torch.tensor(X_val_seq, dtype=torch.float32),
    torch.tensor(y_val_seq, dtype=torch.float32)
)

test_dataset = TensorDataset(
    torch.tensor(X_test_seq, dtype=torch.float32),
    torch.tensor(y_test, dtype=torch.float32)
)

In [58]:
# now that we made sure the dtype are float32 why answer why 
# becos to train our lstms they expect float32 if not can get error or slow training 
"""LSTM is used for RUL prediction because the remaining life of a machine depends 
on how its sensor values change over time, not just on one moment. LSTM can look at many past 
cycles together and learn degradation patterns, which normal models that use only single data points cannot do"""

'LSTM is used for RUL prediction because the remaining life of a machine depends \non how its sensor values change over time, not just on one moment. LSTM can look at many past \ncycles together and learn degradation patterns, which normal models that use only single data points cannot do'

In [59]:
BATCH_SIZE = 64

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

In [60]:
# verification 
xb, yb = next(iter(train_loader))
print(xb.shape)   
print(yb.shape)

torch.Size([64, 30, 14])
torch.Size([64])

In [61]:
# finally done with data 
# now lets get staright to model 
# but the thing if you notice the window size has been intialized randomly with no explanations and mathematical or data backing it 
# why i did it becos now i will run a optuna study to the find the best hyperparameters for model and training 
# but here i am curently using genral rmse not the optimal one which i plan to develop over later datsets where we penlize late reconitions

In [62]:
# defining the baseline model 
import torch.nn as nn

class RUL_LSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, dropout):
        super().__init__()

        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0
        )

        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        return self.fc(out).squeeze(1)

In [63]:
import optuna
import math

In [64]:
def objective(trail):
    input_size = len(feature_cols)
    window_size = trail.suggest_int("window_size",20,50)
    hidden_size = trail.suggest_int("hidden_size",32,256)
    num_hidden_layers = trail.suggest_int("num_hidden_layers",1,3)
    dropout  = trail.suggest_float("dropout",0.0,0.50)
    lr          = trail.suggest_float("lr", 1e-4, 1e-2, log=True)
    batch_size = trail.suggest_categorical("batch_size", [32, 64, 128])
    X_train_seq, y_train_seq = create_sequences(
    train_data_scaled,
     window_size,
    feature_cols,
    TARGET_COL
             )

    X_val_seq, y_val_seq = create_sequences(
         val_data_scaled,
          window_size,
         feature_cols,
         TARGET_COL
            )

    train_dataset = TensorDataset(
        torch.tensor(X_train_seq, dtype=torch.float32),
        torch.tensor(y_train_seq, dtype=torch.float32)
    )
    
    val_dataset = TensorDataset(
        torch.tensor(X_val_seq, dtype=torch.float32),
        torch.tensor(y_val_seq, dtype=torch.float32)
    )
    

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True
    )
    
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False
    )
    
         #self,, input_size, hidden_size, num_layers, dropout
    model = RUL_LSTM(input_size,hidden_size,num_hidden_layers,dropout)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()
    epochs = 10 
    for epoch in range(epochs):
      model.train()
      for X,y in train_loader :
          y_pred = model(X)
          loss = loss_fn(y_pred,y)
          optimizer.zero_grad()
          loss.backward()
          optimizer.step()
    total_loss = 0
    model.eval()
    with torch.no_grad():
      for X,y in val_loader :
          y_pred = model(X)
          loss = loss_fn(y_pred,y)
          total_loss+=loss.item()
    return math.sqrt(total_loss/len(val_loader))

In [65]:
# now finally lets create the study 
study = optuna.create_study(direction = "minimize")
study.optimize(objective, n_trials=30)
print("Best validation RMSE:", study.best_value)
print("Best hyperparameters:", study.best_params)

[I 2026-01-26 09:28:43,946] A new study created in memory with name: no-name-41a0922f-969b-4cb6-847b-ba1ddd15ee5b
[I 2026-01-26 09:30:55,677] Trial 0 finished with value: 68.66124030244134 and parameters: {'window_size': 42, 'hidden_size': 200, 'num_hidden_layers': 2, 'dropout': 0.4046483952998838, 'lr': 0.0001369272051959737, 'batch_size': 64}. Best is trial 0 with value: 68.66124030244134.
[I 2026-01-26 09:32:53,378] Trial 1 finished with value: 35.897487529631235 and parameters: {'window_size': 34, 'hidden_size': 218, 'num_hidden_layers': 1, 'dropout': 0.39485553911111987, 'lr': 0.0028961649112053314, 'batch_size': 32}. Best is trial 1 with value: 35.897487529631235.
[I 2026-01-26 09:37:30,861] Trial 2 finished with value: 33.71054515143126 and parameters: {'window_size': 33, 'hidden_size': 255, 'num_hidden_layers': 2, 'dropout': 0.09700463655831426, 'lr': 0.002041957981210545, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 09:40:14,800] Trial 3 finished with value: 64.25181807529532 and parameters: {'window_size': 34, 'hidden_size': 98, 'num_hidden_layers': 2, 'dropout': 0.19512250863316505, 'lr': 0.007743715725007298, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 09:41:40,708] Trial 4 finished with value: 36.58435787477913 and parameters: {'window_size': 31, 'hidden_size': 229, 'num_hidden_layers': 1, 'dropout': 0.28435191390499437, 'lr': 0.008911030378861106, 'batch_size': 128}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 09:42:14,403] Trial 5 finished with value: 62.69622737636337 and parameters: {'window_size': 37, 'hidden_size': 163, 'num_hidden_layers': 1, 'dropout': 0.2762243252416161, 'lr': 0.00048270589992942004, 'batch_size': 128}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 09:46:34,474] Trial 6 finished with value: 37.90435979481627 and parameters: {'window_size': 27, 'hidden_size': 121, 'num_hidden_layers': 2, 'dropout': 0.11313302564919941, 'lr': 0.0029381756657185744, 'batch_size': 32}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:05:23,280] Trial 7 finished with value: 61.41362003765529 and parameters: {'window_size': 47, 'hidden_size': 224, 'num_hidden_layers': 3, 'dropout': 0.07474579754800986, 'lr': 0.0011171759230570004, 'batch_size': 32}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:15:00,428] Trial 8 finished with value: 34.70568944095213 and parameters: {'window_size': 32, 'hidden_size': 147, 'num_hidden_layers': 2, 'dropout': 0.36731393908531584, 'lr': 0.0018374730938837207, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:17:15,672] Trial 9 finished with value: 63.94586772948965 and parameters: {'window_size': 41, 'hidden_size': 134, 'num_hidden_layers': 2, 'dropout': 0.22652635900897616, 'lr': 0.0006084943822503211, 'batch_size': 128}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:18:35,076] Trial 10 finished with value: 93.17716276381016 and parameters: {'window_size': 21, 'hidden_size': 63, 'num_hidden_layers': 3, 'dropout': 0.017363209773696098, 'lr': 0.00023318888663535506, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:27:35,050] Trial 11 finished with value: 39.539259454036454 and parameters: {'window_size': 27, 'hidden_size': 174, 'num_hidden_layers': 3, 'dropout': 0.4714248862722588, 'lr': 0.0019339933350467921, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:36:15,576] Trial 12 finished with value: 37.52122276935327 and parameters: {'window_size': 27, 'hidden_size': 251, 'num_hidden_layers': 2, 'dropout': 0.34761592721958734, 'lr': 0.0016502628300069692, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:37:46,348] Trial 13 finished with value: 41.87410416173371 and parameters: {'window_size': 21, 'hidden_size': 49, 'num_hidden_layers': 2, 'dropout': 0.15088675778145494, 'lr': 0.0042265691479383026, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:39:45,456] Trial 14 finished with value: 45.95144431967694 and parameters: {'window_size': 38, 'hidden_size': 88, 'num_hidden_layers': 2, 'dropout': 0.48008372209091155, 'lr': 0.0007421502761387697, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 10:53:51,668] Trial 15 finished with value: 64.98600404252058 and parameters: {'window_size': 31, 'hidden_size': 178, 'num_hidden_layers': 3, 'dropout': 0.002858485507051825, 'lr': 0.001230524475770799, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 11:00:36,246] Trial 16 finished with value: 41.304165941494034 and parameters: {'window_size': 49, 'hidden_size': 252, 'num_hidden_layers': 1, 'dropout': 0.3318830868920092, 'lr': 0.0047072418933669915, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 11:02:27,915] Trial 17 finished with value: 44.28512683783694 and parameters: {'window_size': 31, 'hidden_size': 193, 'num_hidden_layers': 2, 'dropout': 0.17219946304816647, 'lr': 0.00037492845344778644, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 11:04:18,957] Trial 18 finished with value: 35.52664001961436 and parameters: {'window_size': 42, 'hidden_size': 155, 'num_hidden_layers': 1, 'dropout': 0.06973210883301746, 'lr': 0.0019498034759745085, 'batch_size': 128}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 11:10:42,495] Trial 19 finished with value: 39.79392721189513 and parameters: {'window_size': 25, 'hidden_size': 109, 'num_hidden_layers': 3, 'dropout': 0.32509452299390085, 'lr': 0.00528044529852939, 'batch_size': 32}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 11:12:17,059] Trial 20 finished with value: 45.97671180235073 and parameters: {'window_size': 38, 'hidden_size': 74, 'num_hidden_layers': 2, 'dropout': 0.41409324603910824, 'lr': 0.0008630802564535153, 'batch_size': 64}. Best is trial 2 with value: 33.71054515143126.
[I 2026-01-26 11:14:15,175] Trial 21 finished with value: 33.25239467256941 and parameters: {'window_size': 44, 'hidden_size': 148, 'num_hidden_layers': 1, 'dropout': 0.07678417893710579, 'lr': 0.0026539217049435463, 'batch_size': 128}. Best is trial 21 with value: 33.25239467256941.
[I 2026-01-26 11:15:32,942] Trial 22 finished with value: 31.107956402399125 and parameters: {'window_size': 45, 'hidden_size': 144, 'num_hidden_layers': 1, 'dropout': 0.11456293885697587, 'lr': 0.003011887241216455, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.
[I 2026-01-26 11:17:12,848] Trial 23 finished with value: 33.9038771567813 and parameters: {'window_size': 45, 'hidden_size': 130, 'num_hidden_layers': 1, 'dropout': 0.11670029544094264, 'lr': 0.002868041919664091, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.
[I 2026-01-26 11:18:21,544] Trial 24 finished with value: 50.82651945083938 and parameters: {'window_size': 50, 'hidden_size': 32, 'num_hidden_layers': 1, 'dropout': 0.05150687327145781, 'lr': 0.0032738026105399542, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.
[I 2026-01-26 11:22:23,578] Trial 25 finished with value: 34.698582775967935 and parameters: {'window_size': 44, 'hidden_size': 196, 'num_hidden_layers': 1, 'dropout': 0.10901772979374696, 'lr': 0.006447040450722105, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.
[I 2026-01-26 11:23:53,786] Trial 26 finished with value: 40.86285437011714 and parameters: {'window_size': 46, 'hidden_size': 115, 'num_hidden_layers': 1, 'dropout': 0.0403977788496208, 'lr': 0.0014030669253665058, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.
[I 2026-01-26 11:25:15,086] Trial 27 finished with value: 36.23502152396704 and parameters: {'window_size': 39, 'hidden_size': 141, 'num_hidden_layers': 1, 'dropout': 0.14792441229539222, 'lr': 0.0024063192157510183, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.
[I 2026-01-26 11:27:45,724] Trial 28 finished with value: 33.61061996231595 and parameters: {'window_size': 48, 'hidden_size': 175, 'num_hidden_layers': 1, 'dropout': 0.20993191033483347, 'lr': 0.0042782123737907345, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.
[I 2026-01-26 11:29:45,214] Trial 29 finished with value: 31.87036223154602 and parameters: {'window_size': 48, 'hidden_size': 173, 'num_hidden_layers': 1, 'dropout': 0.22370944836716822, 'lr': 0.004138331264430279, 'batch_size': 128}. Best is trial 22 with value: 31.107956402399125.

Best validation RMSE: 31.107956402399125
Best hyperparameters: {'window_size': 45, 'hidden_size': 144, 'num_hidden_layers': 1, 'dropout': 0.11456293885697587, 'lr': 0.003011887241216455, 'batch_size': 128}

In [66]:
best = study.best_params

X_train_all, y_train_all = create_sequences(
    pd.concat([train_data_scaled, val_data_scaled]),
    best["window_size"],
    feature_cols,
    TARGET_COL
)

train_all_ds = TensorDataset(
    torch.tensor(X_train_all, dtype=torch.float32),
    torch.tensor(y_train_all, dtype=torch.float32)
)

train_all_loader = DataLoader(
    train_all_ds,
    batch_size=best["batch_size"],
    shuffle=True
)

In [69]:
model = RUL_LSTM(
    input_size=len(feature_cols),
    hidden_size=best["hidden_size"],
    num_layers=best["num_hidden_layers"],
    dropout=best["dropout"]
)

optimizer = torch.optim.Adam(model.parameters(), lr=best["lr"])
criterion = nn.MSELoss()

EPOCHS = 60

for epoch in range(EPOCHS):
    model.train()
    for xb, yb in train_all_loader:

        optimizer.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward()
        optimizer.step()

In [ ]:
torch.save(model.state_dict(), "best_rul_lstm.pth")

In [ ]:
model.eval()
test_preds = []

with torch.no_grad():
    for xb, _ in test_loader:
        xb = xb.to(device)
        test_preds.append(model(xb).cpu())

test_preds = torch.cat(test_preds)
test_rmse = torch.sqrt(torch.mean((test_preds - torch.tensor(y_test))**2))

print("Test RMSE:", test_rmse.item())

In [70]:
torch.save(model.state_dict(), "best_rul_lstm.pth")

In [72]:
model.eval()
test_preds = []

with torch.no_grad():
    for xb, _ in test_loader:
        test_preds.append(model(xb).cpu())

test_preds = torch.cat(test_preds)
test_rmse = torch.sqrt(torch.mean((test_preds - torch.tensor(y_test))**2))

print("Test RMSE:", test_rmse.item())

Test RMSE: 32.17025375366211